# 股池配置示例文件
# 请根据实际情况修改股票名称

stock_pools:
  大概念股池:
    机器人概念:
      - "埃斯顿"
      - "拓斯达"
      - "汇川技术"
      - "新时达"
      - "华中数控"

    电池概念:
      - "宁德时代"
      - "比亚迪"
      - "国轩高科"
      - "亿纬锂能"
      - "天赐材料"

    半导体概念:
      - "中芯国际"
      - "韦尔股份"
      - "兆易创新"
      - "澜起科技"
      - "卓胜微"

    AI概念:
      - "科大讯飞"
      - "海康威视"
      - "大华股份"
      - "浪潮信息"
      - "中科曙光"

  重点关注股池:
    新能源:
      - "隆基绿能"
      - "阳光电源"
      - "通威股份"
      - "爱旭股份"

    医药:
      - "恒瑞医药"
      - "药明康德"
      - "迈瑞医疗"
      - "智飞生物"

  持仓股池:
    当前持仓:
      - "贵州茅台"
      - "五粮液"
      - "招商银行"
      - "中国平安"

# 说明：
# 1. 股池分为三大类：大概念股池、重点关注股池、持仓股池
# 2. 每个股池下可以有多个概念分组
# 3. 每个概念下列出相关股票的中文名称
# 4. 系统会自动将中文名称转换为掘金API所需的股票代码格式